/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/Login'
import { Route as CartImport } from './routes/Cart'
import { Route as ProductImport } from './routes/$product'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  id: '/Cart',
  path: '/Cart',
  getParentRoute: () => rootRoute,
} as any)

const ProductRoute = ProductImport.update({
  id: '/$product',
  path: '/$product',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$product': {
      id: '/$product'
      path: '/$product'
      fullPath: '/$product'
      preLoaderRoute: typeof ProductImport
      parentRoute: typeof rootRoute
    }
    '/Cart': {
      id: '/Cart'
      path: '/Cart'
      fullPath: '/Cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$product': typeof ProductRoute
  '/Cart': typeof CartRoute
  '/Login': typeof LoginRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$product': typeof ProductRoute
  '/Cart': typeof CartRoute
  '/Login': typeof LoginRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$product': typeof ProductRoute
  '/Cart': typeof CartRoute
  '/Login': typeof LoginRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$product' | '/Cart' | '/Login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$product' | '/Cart' | '/Login'
  id: '__root__' | '/' | '/$product' | '/Cart' | '/Login'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductRoute: typeof ProductRoute
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductRoute: ProductRoute,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$product",
        "/Cart",
        "/Login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$product": {
      "filePath": "$product.tsx"
    },
    "/Cart": {
      "filePath": "Cart.tsx"
    },
    "/Login": {
      "filePath": "Login.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
